# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "single_test"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = "2012-03-07"
  s.email = "grosser.michael@gmail.com"
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "lib/single_test.rb",
    "lib/tasks/single_test.rake",
    "single_test.gemspec",
    "spec/example_finder_test.txt",
    "spec/single_test_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/grosser/single_test"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Rake tasks to invoke single tests/specs with rakish syntax"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, ["> 0.9"])
    else
      s.add_dependency(%q<rake>, ["> 0.9"])
    end
  else
    s.add_dependency(%q<rake>, ["> 0.9"])
  end
end

