# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "single_test"
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = "2011-10-23"
  s.email = "grosser.michael@gmail.com"
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "lib/single_test.rb",
    "lib/tasks/single_test.rake",
    "single_test.gemspec",
    "spec/example_finder_test.txt",
    "spec/single_test_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/grosser/single_test"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Rake tasks to invoke single tests/specs with rakish syntax"
  s.test_files = [
    "spec/single_test_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

